FOLDER_PATH = r""Your public folder path for attacker site + \public"
DB_NAME = "YOUR_DB_NAME"
USER_NAME = "YOUR_USER_NAME"
PASSWORD = "YOUR_PASSWORD"
HOST = "localhost"
TABLE = "simulation_results"

MAILID = "YOUR_SMTP_MAIL_ID/CREDENTIALS"
MAIL_PASSWORD = "YOUR_SMTP_PASSWORD/CREDENTIALS"
MAIL_PORT = YOUR_SMTP_PORT 
MAIL_SERVER = "YOUR_SMTP_SERVER_ADDRESS"
